jenkins-infra/docker-openvpn

docker/config/auth-ldap.conf, docker/docker-compose.yaml, docker/entrypoint.sh
=> [INFRA-2893] Feat: remove the custom CA to rely on the ca-certificate bundle

Jenkinsfile_k8s, updatecli/updatecli.d/golang.yaml, updatecli/updatecli.d/hashicorp-tools.yml
upgrading manifest to be compliant with new scm formating
=> chore reworking updatecli manifest

updatecli/updatecli.d/golang.yaml
correct the updatecli manifest to create a pull request on goland version update.
=> chore (updatecli): add the pullrequest for go version update

README.md
Following #152 , this PR correct the readme to mention the github issue tracker (instead of the old jira) + other fixes to help users
=> Chore: fix readme

Jenkinsfile_k8s, README.md, updatecli/updatecli.d/golang.yaml, updatecli/updatecli.d/hashicorp-tools.yml
=> chores: add a note about client VPN username + password + fix updatecli manifests for 0.23.x

Jenkinsfile_k8s, updatecli/updatecli.d/golang.yaml, updatecli/updatecli.d/hashicorp-tools.yml
=> chore(updatecli) fix manifests for updatecli v0.33.x

updatecli/updatecli.d/golang.yaml, updatecli/updatecli.d/hashicorp-tools.yml
=> chore(updatecli) fix manifests for 0.36.x and add a condition for golang

updatecli/updatecli.d/golang.yaml, updatecli/updatecli.d/hashicorp-tools.yml
=> chore(updatecli) remove deprecated directives for 0.40.x

Dockerfile, docker/config/auth-ldap.conf, docker/entrypoint.sh
Work in progress around https://github.com/jenkins-infra/helpdesk/issues/2982
=> breaking: bump Ubuntu to 22.04

cert/ccd/private/danielbeck, cert/ccd/private/dduportal, cert/ccd/private/halkeye, cert/ccd/private/hlemeur, cert/ccd/private/kevingrdj, cert/ccd/private/markewaite, cert/ccd/private/notmyfault, cert/ccd/private/smerle, cert/ccd/private/timja, cert/ccd/private/wfollonier, cert/ccd/private/yafenkin, config.yaml
Follow up of https://github.com/jenkins-infra/jenkins-infra/pull/2858, related to https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1562482092 to add these routes on VPN client sides
=> feat(private) add routes to the public and public-db vnets

cert/ccd/private/danielbeck, cert/ccd/private/dduportal, cert/ccd/private/hlemeur, cert/ccd/private/kevingrdj, cert/ccd/private/notmyfault, cert/ccd/private/smerle, cert/ccd/private/timja, cert/ccd/private/wfollonier, cert/ccd/private/yafenkin, config.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/3624
=> feat(ccds) allow some users to route to trusted-ci-jenkins-io vnet

cert/ccd/private/danielbeck, cert/ccd/private/dduportal, cert/ccd/private/halkeye, cert/ccd/private/hlemeur, cert/ccd/private/kevingrdj, cert/ccd/private/krisstern, cert/ccd/private/lemeurherveCB, cert/ccd/private/markewaite, cert/ccd/private/notmyfault, cert/ccd/private/smerle, cert/ccd/private/smerleCB, cert/ccd/private/timja, cert/ccd/private/wfollonier, cert/ccd/private/yafenkin
as per 
- https://github.com/jenkins-infra/helpdesk/issues/3923#issuecomment-2161174430
the vnet size has changed, it imply update in few places
=> feat(infra-ci-sponsorship): extend vnet for all user

updatecli/scripts/netmask.sh, updatecli/updatecli.d/restricted-ips.yaml
Following https://github.com/jenkins-infra/docker-openvpn/pull/374
and as public-db vnet is 10.253.0.0/21 as per [jenkins-infra/azure-net@153e2d6/vnets.tf#L436](https://github.com/jenkins-infra/azure-net/blob/153e2d6a30c6a9979a5fa7994a758e448fa3a911/vnets.tf#L436)
see https://reports.jenkins.io/jenkins-infra-data-reports/azure-net.json
tested locally:
```
⚠ - 9 file(s) updated with "# public-db vnet\npush \"route 10.253.0.0 255.255.248.0\"\n":
* cert/ccd/private/notmyfault
* cert/ccd/private/timja
* cert/ccd/private/dduportal
* cert/ccd/private/kevingrdj
* cert/ccd/private/markewaite
* cert/ccd/private/wfollonier
* cert/ccd/private/danielbeck
* cert/ccd/private/krisstern
* cert/ccd/private/smerle
ACTIONS
========
Update list of IPs restricted to VPN access only & update vnets - default …
```
=> chore(updatecli): add azure-public-db-vnet in the manifest and calcul netmask

cert/ccd/private/abayer, cert/ccd/private/danielbeck, cert/ccd/private/dduportal, cert/ccd/private/jayfranco_cb, cert/ccd/private/kevingrdj, cert/ccd/private/kohsuke, cert/ccd/private/krisstern, cert/ccd/private/markewaite, cert/ccd/private/notmyfault, cert/ccd/private/smerle, cert/ccd/private/swapna_01, cert/ccd/private/timja, cert/ccd/private/wfollonier, config.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4620
The IPv4 value comes from https://reports.jenkins.io/jenkins-infra-data-reports/azure.json
An updatecli subsequent PR is expected
=> feat(ccds): add route for azure.ci.jenkins.io

cert/ccd/private/abayer, cert/ccd/private/danielbeck, cert/ccd/private/dduportal, cert/ccd/private/jayfranco_cb, cert/ccd/private/kevingrdj, cert/ccd/private/kohsuke, cert/ccd/private/krisstern, cert/ccd/private/markewaite, cert/ccd/private/notmyfault, cert/ccd/private/smerle, cert/ccd/private/swapna_01, cert/ccd/private/timja, cert/ccd/private/wfollonier, config.yaml, updatecli/updatecli.d/restricted-ips.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4620
=> cleanup: remove aws.ci.jenkins.io and cijenkinsio-agents-2 references

cert/ccd/private/abayer, cert/ccd/private/danielbeck, cert/ccd/private/dduportal, cert/ccd/private/kevingrdj, cert/ccd/private/krisstern, cert/ccd/private/markewaite, cert/ccd/private/notmyfault, cert/ccd/private/smerle, cert/ccd/private/timja, cert/ccd/private/wfollonier, config.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2797439659
=> feat(ccds) add routing to the new private_sponsored vnet

cert/ccd/private/jayfranco_cb
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2839488075
=> fix(ccd) set up jayfranco_cb routes

README.md, config.yaml, updatecli/updatecli.d/restricted-ips.yaml, utils/easyvpn/checks/main.go
- chore(updatecli) fix manifest tracking public-db route. Fixup of #410
- chore(easyvpn,readme) fixup server side certificate handling
=> chore(updatecli) fix failing manifests

utils/easyvpn/checks/main.go, utils/easyvpn/cmd/config.go, utils/easyvpn/cmd/request.go, utils/easyvpn/cmd/revoke.go, utils/easyvpn/cmd/sign.go, utils/easyvpn/easyrsa/main.go, utils/easyvpn/helpers/main.go, utils/easyvpn/network/main.go
A set of minor code fixes recommended by VSCode, by Golang compiler and by `golangci-lint`
=> chore(easyvpn) apply go lint recommendation for better code

cert/ccd/private/danielbeck, cert/ccd/private/dduportal, cert/ccd/private/jayfranco_cb, cert/ccd/private/kevingrdj, cert/ccd/private/markewaite, cert/ccd/private/notmyfault, cert/ccd/private/smerle, cert/ccd/private/timja, cert/ccd/private/wfollonier, config.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4689#issuecomment-2961894408
add the vnet for infraciagents2 for the VPN to access it (client side version)
=> feat(config): add routing for infraciagents2 vnet

cert/ccd/private/danielbeck, cert/ccd/private/dduportal, cert/ccd/private/jayfranco_cb, cert/ccd/private/kevingrdj, cert/ccd/private/markewaite, cert/ccd/private/notmyfault, cert/ccd/private/smerle, cert/ccd/private/timja, cert/ccd/private/wfollonier, config.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4688
Follows up EKS cluster creation in https://github.com/jenkins-infra/terraform-aws-sponsorship/pull/249
=> feat: add routes to the new AWS EKS cluster API

cert/ccd/private/danielbeck, cert/ccd/private/dduportal, cert/ccd/private/jayfranco_cb, cert/ccd/private/kevingrdj, cert/ccd/private/markewaite, cert/ccd/private/notmyfault, cert/ccd/private/smerle, cert/ccd/private/timja, cert/ccd/private/wfollonier, config.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4644#issuecomment-3032760767
=> feat(config/ccd) add a new route to testissues.jenkins.io

cert/ccd/private/abayer, cert/ccd/private/danielbeck, cert/ccd/private/dduportal, cert/ccd/private/jayfranco_cb, cert/ccd/private/kevingrdj, cert/ccd/private/kohsuke, cert/ccd/private/krisstern, cert/ccd/private/markewaite, cert/ccd/private/notmyfault, cert/ccd/private/smerle, cert/ccd/private/timja, cert/ccd/private/wfollonier, config.yaml, updatecli/values.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4688
=> cleanup(config/ccd/updatecli) remove remnants of azure.ci.jenkins.io

cert/ccd/private/danielbeck, cert/ccd/private/dduportal, cert/ccd/private/jayfranco_cb, cert/ccd/private/kevingrdj, cert/ccd/private/markewaite, cert/ccd/private/notmyfault, cert/ccd/private/smerle, cert/ccd/private/timja, cert/ccd/private/wfollonier, config.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/1626
following https://github.com/jenkins-infra/digitalocean/pull/255
adding the ipv4 of the VM in the routes of the VPN
=> feat: add a new route for do.usage.jenkins.io
