.github/release-drafter.yml
The purpose of this is to build docker images using a well identified release version.
=> Enable release-drafter on jenkins-infra/openvpn

updatecli/updatecli.d/golang.yaml
With the original regexp, `go1.18-beta` is matched
=> fix: add delimiter to avoid matching "-beta" versions

utils/easyvpn/Makefile, utils/easyvpn/go.mod, utils/easyvpn/go.sum
- https://github.com/advisories/GHSA-77vh-xpmg-72qh
- https://github.com/advisories/GHSA-g54h-m393-cpwq
also, this PR cleans up the unwanted `GOOS` env. var passed to containers when building easyvpn (that should help on building on windows)
=> fix(easyvpn) bump dependencies to fix security alerts

docker/entrypoint.sh
=> fix: fail if `OPENVPN_NETWORK` is undefined in Docker entrypoint script

README.md, docker/config/server.conf, docker/docker-compose.yaml, docker/entrypoint.sh
Allow changing server.conf values with env vars
Follow-up of https://github.com/jenkins-infra/docker-openvpn/pull/212
=> fix: customizable OpenVPN `server.conf`

.github/workflows/release-drafter.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/3402
=> chore: pin GitHub actions with their SHA-1 instead of their version number

updatecli/updatecli.d/golang.yaml
Noticed the following error in https://infra.ci.jenkins.io/blue/organizations/jenkins/docker-jobs%2Fdocker-openvpn/detail/PR-242/4/pipeline:
> [2023-02-24T13:18:08.749Z] updateGomod
> [2023-02-24T13:18:08.749Z] -----------
> [2023-02-24T13:18:08.749Z] 
> [2023-02-24T13:18:08.749Z] **Dry Run enabled**
> [2023-02-24T13:18:08.750Z] 
> [2023-02-24T13:18:08.807Z] vendor/golang.org/x/text/unicode/bidi
> [2023-02-24T13:18:08.807Z] vendor/golang.org/x/text/unicode/norm
> [2023-02-24T13:18:09.008Z] ✔ Content from file "/tmp/updatecli/github/jenkins-infra/openvpn/utils/easyvpn/go.mod" already up to date
> [2023-02-24T13:18:09.008Z] ✔ All contents from 'file' and 'files' combined already up to date
> [2023-02-24T13:18:09.008Z] 
> [2023-02-24T13:18:09.008Z] ERROR: something went wrong in target …
=> fix(updatecli): remove Jenkinsfile_k8s target for the golang manifest

updatecli/scripts/updateGomodGoversion.sh
The script used any existing installation of golang but:
- As soon as it uses a non PATH-located directory (or management tooling such as `asdf`) then it fails
- There is a dependency on the existing golang installation while we want the new version
=> chore(updatecli) fix golang mod update script

cert/ccd/private/danielbeck, cert/ccd/private/dduportal, cert/ccd/private/hlemeur, cert/ccd/private/kevingrdj, cert/ccd/private/smerle, cert/ccd/private/wfollonier, cert/ccd/private/yafenkin, config.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/3688
This PR adds **manually** the routing rule on a few selected users to allow their VPN setup to route to the cert-ci-jenkins-io network.
=> feat: allow routing to cert-ci vnet for JenSec and JenInfra team members

cert/ccd/private/danielbeck, cert/ccd/private/dduportal, cert/ccd/private/halkeye, cert/ccd/private/hlemeur, cert/ccd/private/kevingrdj, cert/ccd/private/krisstern, cert/ccd/private/lemeurherveCB, cert/ccd/private/markewaite, cert/ccd/private/notmyfault, cert/ccd/private/smerle, cert/ccd/private/smerleCB, cert/ccd/private/timja, cert/ccd/private/wfollonier, cert/ccd/private/yafenkin
Since https://github.com/jenkins-infra/helpdesk/issues/3818, there is a whole lot bunch of new virtual networks.
Our VPN setups should be aware of these new routes otherwise we can't reach new VMs such as in https://github.com/jenkins-infra/helpdesk/issues/3913
For proper review or audit: list of vnet and their CIDRs are defined here: https://github.com/jenkins-infra/azure-net/blob/main/vnets.tf
=> feat: add the new (sponsored) vnet routes to CCDs

Jenkinsfile_k8s
as per https://github.com/jenkins-infra/docker-openvpn/pull/328#issuecomment-1945555172
I forgot to update this pipeline to use the new allinone agent
=> chore(pipeline) use "all in one" `arm64` agent instead of `amd64` deprecated `jenkinsciinfra/hashicorp-tools` 

cert/ccd/private/danielbeck, cert/ccd/private/dduportal, cert/ccd/private/hlemeur, cert/ccd/private/kevingrdj, cert/ccd/private/markewaite, cert/ccd/private/notmyfault, cert/ccd/private/smerle, cert/ccd/private/timja, cert/ccd/private/wfollonier, config.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4196
This PR adds the routes to the CCDs of the "usual suspects" and to the default configuration for new CCDs.
=> feat(ccds) add routes to the pkg, census, usage and archives VM through the VPN

updatecli/updatecli.d/restricted-ips.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4315
=> chore(updatecli) track ci.jenkins.io public IP to keep routing up to date

cert/ccd/private/danielbeck, cert/ccd/private/dduportal, cert/ccd/private/jayfranco_cb, cert/ccd/private/kevingrdj, cert/ccd/private/markewaite, cert/ccd/private/notmyfault, cert/ccd/private/smerle, cert/ccd/private/timja, cert/ccd/private/wfollonier, config.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4319
Twin (client-side) of https://github.com/jenkins-infra/jenkins-infra/pull/3776
Current endpoint hostname is `BFED49033BB86D3FF1EF8DE8480E024B.gr7.us-east-2.eks.amazonaws.com` which resolve to 2 public IPv4s.
=> feat(ccd) add 2 routes to the EKS cluster `cijenkinsio-agents-2`

updatecli/scripts/createIssue.sh
as per https://github.com/jenkins-infra/helpdesk/issues/4534
=> chore(updatecli) fix crl issue creation

.github/workflows/release-drafter.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/2982
=> chore(GHA) use `ubuntu-latest` runner for Release Drafter

updatecli/values.yaml
This PR separates updatecli to its own pipeline and uses https://github.com/apps/jenkins-infra-updatecli instead of https://github.com/jenkins-infra-bot in updatecli values.
Note: no arm64 image.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/2778
=> chore: separate updatecli to its own pipeline

config.yaml, utils/easyvpn/cmd/config.go, utils/easyvpn/cmd/sign.go, utils/easyvpn/network/main.go
As https://github.com/jenkins-infra/docker-openvpn/pull/404 shows, using an array to express the networks is fragile: keeping it up to date (with `updatecli` or any other tool) depends on the order.
This PR changes the code of `easyvpn` to that we use a map: no order as we use the networks name as keys instead.
Tested localy with the new `easyvpn` go build with:
- Trying to generater a new user `foo` and checked its CCD is ok:
```
./easyvpn request --commit=false --push=false foo
./easyvpn sign --commit=false --push=false foo
```
- Tested the command `easyvpn check` is still successful and shows the production certs.
=> feat(easyvpn)!: use map for networks in YAML config

Jenkinsfile_k8s, utils/easyvpn/Makefile, utils/easyvpn/cmd/config.go, utils/easyvpn/cmd/request.go, utils/easyvpn/cmd/revoke.go, utils/easyvpn/cmd/sign.go, utils/easyvpn/git/main.go, utils/easyvpn/helpers/main.go, utils/easyvpn/network/main.go
- Lint enabled with a new Make target: `lint`,
- which is called by the pipeline
- Applied all messages from the linter (a lot of ineffectual assignemnt, missing `errchecks`, unused variables, etc.)
- Note: We rely on the `golangci-lint` installed on the agents machines (https://github.com/jenkins-infra/packer-images/blob/68eba541d19885223144cd6d32eca550688e9f7d/provisioning/tools-versions.yml#L17)
=> chore(easyvpn) enable golangci lint and fix checker warnings

utils/easyvpn/cmd/config.go, utils/easyvpn/cmd/main.go, utils/easyvpn/cmd/sign.go
Calling the command `./easyvpn config --push=false dduportal` did push the commited changes despite the flag set to `false`.
This PR aims at fixing this bug.
=> fix(easyvpn) ensure that the git behavior (commit, push) maps to user provided flags

utils/easyvpn/cmd/check.go, utils/easyvpn/cmd/config.go, utils/easyvpn/cmd/main.go, utils/easyvpn/cmd/request.go, utils/easyvpn/cmd/revoke.go, utils/easyvpn/cmd/root.go, utils/easyvpn/cmd/sign.go
Follow up of #414 , extracted from #415
The  `request` and `revoke` commands were not fulfilling properly the provided flags.
This PR is a pass on all the cobra commands to unify the flags
=> fix(easyvpn) ensure user provided flags behave as expected

cert/ccd/private/abayer, cert/ccd/private/danielbeck, cert/ccd/private/dduportal, cert/ccd/private/jayfranco_cb, cert/ccd/private/kevingrdj, cert/ccd/private/kohsuke, cert/ccd/private/krisstern, cert/ccd/private/markewaite, cert/ccd/private/notmyfault, cert/ccd/private/smerle, cert/ccd/private/timja, cert/ccd/private/wfollonier, config.yaml, utils/easyvpn/clientconfig/main.go
As we want to keep track of IP associated to multi-valued DNS records (usually AWS ELBs), it is easier if we specify multiple IPs per network route
=> feat(easyvpn/config) allow specifying multiple CIDR per route with space (' ') as separator

cert/ccd/private/danielbeck, cert/ccd/private/dduportal, cert/ccd/private/jayfranco_cb, cert/ccd/private/kevingrdj, cert/ccd/private/markewaite, cert/ccd/private/notmyfault, cert/ccd/private/smerle, cert/ccd/private/timja, cert/ccd/private/wfollonier, config.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4769
This PR allows admins to access the registry through VPN routing (as it is only reachable through private endpoints)
=> feat(config) add a new route for `dockerhubmirror.privatelink.azurecr.io`

updatecli/updatecli.d/restricted-ips.yaml.tpl, updatecli/values.yaml
Closes https://github.com/jenkins-infra/docker-openvpn/pull/464
Following #463 , related to https://github.com/jenkins-infra/helpdesk/issues/1626
=> chore(updatecli) update tracking of IP with usage.jenkins.io in DigitalOcean and deprecation messages with JSON resource
